export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"; 
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_PROPERTY_REQUEST = "FETCH_PROPERTY_REQUEST";
export const FETCH_PROPERTY_SUCCESS = "FETCH_PROPERTY_SUCCESS"; 
export const FETCH_PROPERTY_FAILURE = "FETCH_PROPERTY_FAILURE";

export const FETCH_HOST_PROPERTY_REQUEST = "FETCH_HOST_PROPERTY_REQUEST";
export const FETCH_HOST_PROPERTY_SUCCESS = "FETCH_HOST_PROPERTY_SUCCESS";
export const FETCH_HOST_PROPERTY_FAILURE = "FETCH_HOST_PROPERTY_FAILURE";


export const FETCH_PROPERTYTYPE_REQUEST = "FETCH_PROPERTYTYPE_REQUEST";
export const FETCH_PROPERTYTYPE_SUCCESS = "FETCH_PROPERTYTYPE_SUCCESS";
export const FETCH_PROPERTYTYPE_FAILURE = "FETCH_PROPERTYTYPE_FAILURE";

export const FETCH_PROPERTY_OPTIONS_REQUEST = "FETCH_PROPERTY_OPTIONS_REQUEST";
export const FETCH_PROPERTY_OPTIONS_SUCCESS = "FETCH_PROPERTY_OPTIONS_SUCCESS";
export const FETCH_PROPERTY_OPTIONS_FAILURE = "FETCH_PROPERTY_OPTIONS_FAILURE";

export const GET_SELECTED_PRIVACY_BY_ID_REQUEST = "GET_SELECTED_PRIVACY_BY_ID_REQUEST";
export const GET_SELECTED_PRIVACY_BY_ID_SUCCESS = "GET_SELECTED_PRIVACY_BY_ID_SUCCESS";
export const GET_SELECTED_PRIVACY_BY_ID_FAILURE = "GET_SELECTED_PRIVACY_BY_ID_FAILURE";


export const GET_PROPERTY_BYID_REQUEST = "GET_PROPERTY_BYID_REQUEST";
export const GET_PROPERTY_BYID_SUCCESS = "GET_PROPERTY_BYID_SUCCESS";
export const GET_PROPERTY_BYID_FAILURE = "GET_PROPERTY_BYID_FAILURE";


export const UPDATE_PROPERTY_LOCATION_REQUEST = "UPDATE_PROPERTY_LOCATION_REQUEST";
export const UPDATE_PROPERTY_LOCATION_SUCCESS = "UPDATE_PROPERTY_LOCATION_SUCCESS";
export const UPDATE_PROPERTY_LOCATION_FAILURE = "UPDATE_PROPERTY_LOCATION_FAILURE";

export const UPDATE_PROPERTY_STEP_REQUEST = "UPDATE_PROPERTY_STEP_REQUEST";
export const UPDATE_PROPERTY_STEP_SUCCESS = "UPDATE_PROPERTY_STEP_SUCCESS";
export const UPDATE_PROPERTY_STEP_FAILURE = "UPDATE_PROPERTY_STEP_FAILURE";