export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"; 
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_PROPERTY_REQUEST = "FETCH_PROPERTY_REQUEST";
export const FETCH_PROPERTY_SUCCESS = "FETCH_PROPERTY_SUCCESS"; 
export const FETCH_PROPERTY_FAILURE = "FETCH_PROPERTY_FAILURE";

export const FETCH_HOST_PROPERTY_REQUEST = "FETCH_HOST_PROPERTY_REQUEST";
export const FETCH_HOST_PROPERTY_SUCCESS = "FETCH_HOST_PROPERTY_SUCCESS";
export const FETCH_HOST_PROPERTY_FAILURE = "FETCH_HOST_PROPERTY_FAILURE";


export const FETCH_PROPERTYTYPE_REQUEST = "FETCH_PROPERTYTYPE_REQUEST";
export const FETCH_PROPERTYTYPE_SUCCESS = "FETCH_PROPERTYTYPE_SUCCESS";
export const FETCH_PROPERTYTYPE_FAILURE = "FETCH_PROPERTYTYPE_FAILURE";

export const FETCH_PROPERTY_OPTIONS_REQUEST = "FETCH_PROPERTY_OPTIONS_REQUEST";
export const FETCH_PROPERTY_OPTIONS_SUCCESS = "FETCH_PROPERTY_OPTIONS_SUCCESS";
export const FETCH_PROPERTY_OPTIONS_FAILURE = "FETCH_PROPERTY_OPTIONS_FAILURE";